services:
  app:
    build: .
    ports:
      - 3000:3000
    restart: always
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 2
    #   start_period: 30s
